
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php74
      - php82
      - pamp_node
    networks:
      - webnet
    restart: unless-stopped

  php74:
    build:
      context: ./php
      args:
        PHP_VERSION: "7.4"
    container_name: php74
    volumes:
      - ./www:/var/www/html
    environment:
      - PHP_MAX_EXECUTION_TIME=3000
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
      - PHP_MAX_INPUT_VARS=30000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet
    restart: unless-stopped

  php82:
    build:
      context: ./php
      args:
        PHP_VERSION: "8.2"
    container_name: php82
    volumes:
      - ./www:/var/www/html
    environment:
      - PHP_MAX_EXECUTION_TIME=3000
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
      - PHP_MAX_INPUT_VARS=30000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet
    restart: unless-stopped

  pamp_node:
    image: node:18-alpine
    container_name: pamp_node
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./www/pamp:/usr/src/app
      - pamp_node_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DB_HOST=mariadb
      - DB_USER=gomgift
      - DB_PASSWORD=Gomgift00
      - DB_NAME=yc_gomgift
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- -H 0.0.0.0"
    networks:
      - webnet
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dudtlr00
      MYSQL_DATABASE: yc_gomgift
      MYSQL_USER: gomgift
      MYSQL_PASSWORD: Gomgift00
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  pamp_node_node_modules:
    driver: local